### ISSUE TITLE
clicking the cart button opens a new tab/window

### ISSUE THREAD

**Issue by Volkanite** [Volkanite/catropolis#22]
Is this the desired functionality? It feels weird because I click the cart button often. Then I end up with lots of tabs/windows.

**Comment by Huan-Ting** [comment]
No,it's not the desired functionality. Just it was not the top priority until now, other main functions are working properly :)   This is something we can fix ~

**Comment by Huan-Ting** [comment]
Accidentally add a attribution to link tag... fixed!

**Comment by Volkanite** [comment]
Fixed by c3d962157732c77e1f093f1d67109b654744796e
